---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  build-init-image
  namespace: kpack
data:
  image: |
    gcr.io/cf-build-service-public/kpack/build-init:{{.kpack.imageVersions.buildInit | default "na"}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  build-init-windows-image
  namespace: kpack
data:
  image: |
    gcr.io/cf-build-service-public/kpack/build-init-windows:{{.kpack.imageVersions.buildInitWindows  | default "na"}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  rebase-image
  namespace: kpack
data:
  image: |
    gcr.io/cf-build-service-public/kpack/rebase:{{.kpack.imageVersions.rebase  | default "na"}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  lifecycle-image
  namespace: kpack
data:
  image: |
    gcr.io/cf-build-service-public/kpack/lifecycle:{{.kpack.imageVersions.lifecycle | default "na"}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  completion-image
  namespace: kpack
data:
  image: |
    gcr.io/cf-build-service-public/kpack/completion:{{.kpack.imageVersions.completion | default "na"}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  completion-windows-image
  namespace: kpack
data:
  image: |
    gcr.io/cf-build-service-public/kpack/completion-windows:{{.kpack.imageVersions.completionWindows | default "na"}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.2.2
    spec:
      serviceAccountName: controller
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: controller
          image: |
            gcr.io/cf-build-service-public/kpack/controller:{{.kpack.imageVersions.controller | default "na"}}