apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: webhook
        version: 0.2.2
    spec:
      serviceAccountName: webhook
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: webhook
          image: |
            gcr.io/cf-build-service-public/kpack/webhook:{{.kpack.imageVersions.webhook | default "na"}}