# Adds namespace to all resources.
namespace: platform-system

images:
  - name: controller
    newName: docker.io/flanksource/konfig-manager
    newTag: '{{.konfigManager.version | default "na" }}'
resources:
  # rbac files
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/service_account.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/role.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/role_binding.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/leader_election_role.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/leader_election_role_binding.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/auth_proxy_service.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/auth_proxy_role.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/auth_proxy_role_binding.yaml
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/rbac/auth_proxy_client_clusterrole.yaml

  ## manager files
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/manager/manager.yaml

patchesStrategicMerge:
  - https://raw.githubusercontent.com/flanksource/konfig-manager/main/config/base/manager_auth_proxy_patch.yaml
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: konfig-manager
      namespace: system
    spec:
      template:
        spec:
          containers:
            - name: konfig-manager
              args:
                - "operator"
                - "--health-probe-bind-address=:8082"
                - "--metrics-bind-address=127.0.0.1:8081"
                - "--leader-elect"
                - "--sync-period={{ .konfigManager.syncPeriod | default \"10m\" }}"
              resources:
                limits:
                  cpu: 150m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 150Mi