apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java
    - image: gcr.io/paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: test-builder
  namespace: kpack
spec:
  serviceAccount: default
  tag: ttl.sh/test-builder-for-kpack-{{ random.String 7 `[a-z]` }}:15m
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: test-image
  namespace: kpack
spec:
  tag: ttl.sh/test-image-for-kpack-{{ random.String 7 `[a-z]` }}:15m
  serviceAccount: default
  builder:
    name: test-builder
    kind: Builder
    namespace: kpack
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4