---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keptn-api-token
  labels:
    app.kubernetes.io/name: keptn-api-token
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
type: Opaque
data:
  keptn-api-token: "RzBmTlNIQ3Fyd0RoZmxrU1BOT2ZNeEdlcnE4S281cmZlVWF0UVhKbkhua1Rs"
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bridge-credentials
  labels:
    app.kubernetes.io/name: bridge-credentials
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3  
type: Opaque
data:
  BASIC_AUTH_USERNAME: 'a2VwdG4='
  BASIC_AUTH_PASSWORD: "NFBrU2VPOVUwNGZLemxJeGV5Umk="
---
# Source: keptn/charts/control-plane/templates/core.yaml
# configuration-service
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: configuration-volume
  labels:
    app.kubernetes.io/name: configuration-volume
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3     
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  100Mi
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3  
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Service
metadata:
  name: bridge
  labels:
    app.kubernetes.io/name: bridge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3      
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: bridge
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Service
metadata:
  name: event-broker
  labels:
    app.kubernetes.io/name: eventbroker-go
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3      
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: eventbroker-go
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Service
metadata:
  name: shipyard-service
  labels:
    app.kubernetes.io/name: shipyard-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3   
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: shipyard-service
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  labels:
    app.kubernetes.io/name: configuration-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3   
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: configuration-service
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-service
      app.kubernetes.io/instance: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-service
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3    
    spec:
      containers:
        - name: api-service
          image: docker.io/keptn/api:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: PREFIX_PATH
              value: ""
            - name: EVENTBROKER_URI
              value: event-broker
            - name: DATASTORE_URI
              value: mongodb-datastore:8080
            - name: CONFIGURATION_URI
              value: configuration-service:8080
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keptn-api-token
                  key: keptn-api-token
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: keptn-api-service
---
# Source: keptn/charts/control-plane/templates/core.yaml
# bridge
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  labels:
    app.kubernetes.io/name: bridge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3      
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bridge
      app.kubernetes.io/instance: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bridge
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3      
    spec:
      containers:
        - name: bridge
          image: docker.io/keptn/bridge2:0.7.3
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: "http://api-gateway-nginx/api"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keptn-api-token
                  key: keptn-api-token
            - name: CLI_DOWNLOAD_LINK
              value: "https://github.com/keptn/keptn/releases/tag/0.7.3"
            - name: INTEGRATIONS_PAGE_LINK
              value: "https://get.keptn.sh/integrations.html"
            - name: ENABLE_VERSION_CHECK
              value: "true"
            - name: SHOW_API_TOKEN
              value: "true"
            - name: KEPTN_INSTALLATION_TYPE
              value: "QUALITY_GATES,CONTINUOUS_OPERATIONS"
          envFrom:
            - secretRef:
                name: bridge-credentials
                optional: true
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      serviceAccountName: keptn-default
---
# Source: keptn/charts/control-plane/templates/core.yaml
# eventbroker-go
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbroker-go
  labels:
    app.kubernetes.io/name: eventbroker-go
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3      
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eventbroker-go
      app.kubernetes.io/instance: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventbroker-go
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3      
    spec:
      containers:
        - name: eventbroker-go
          image: docker.io/keptn/eventbroker-go:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_IMPL
              value: 'nats'
      serviceAccountName: keptn-default
---
# Source: keptn/charts/control-plane/templates/core.yaml
# shipyard-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipyard-service
  labels:
    app.kubernetes.io/name: shipyard-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3      
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shipyard-service
      app.kubernetes.io/instance: RELEASE-NAME      
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shipyard-service
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3   
    spec:
      containers:
        - name: shipyard-service
          image: docker.io/keptn/shipyard-service:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: API
              value: 'ws://api-service:8080/websocket'
        - name: distributor
          image: docker.io/keptn/distributor:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.internal.event.project.create,sh.keptn.internal.event.project.delete,sh.keptn.internal.event.service.create,sh.keptn.internal.event.service.delete'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-default
---
# Source: keptn/charts/control-plane/templates/core.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
  labels:
    app.kubernetes.io/name: configuration-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3     
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: configuration-service
      app.kubernetes.io/instance: RELEASE-NAME
  replicas: 1
  # recreate the deployment if anything changes (we can not do a rolling upgrade of this deployment as we use a volume)
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: configuration-service
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3   
    spec:
      containers:
        - name: configuration-service
          image: docker.io/keptn/configuration-service:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          env:
            - name: PREFIX_PATH
              value: ""
            - name: MONGODB_HOST
              value: 'mongodb:27017'
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
            - name: MONGO_DB_NAME
              value: 'keptn'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /data/config
              name: configuration-volume
        - name: distributor
          image: docker.io/keptn/distributor:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: PUBSUB_RECIPIENT_PATH
              value: '/v1/event'
      volumes:
        - name: configuration-volume
          persistentVolumeClaim:
            claimName: configuration-volume
      serviceAccountName: keptn-configuration-service
