---
# Source: keptn/charts/control-plane/templates/mongodb-datastore.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-datastore
  labels:
    app.kubernetes.io/name: mongodb-datastore
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3         
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: mongodb-datastore
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/mongodb-datastore.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-datastore
  annotations:
    fluentbit.io/exclude: "true"
  labels:
    app.kubernetes.io/name: mongodb-datastore
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3     
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb-datastore
      app.kubernetes.io/instance: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-datastore
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3     
    spec:
      serviceAccountName: keptn-default
      containers:
      - name: mongodb-datastore
        image: docker.io/keptn/mongodb-datastore:0.7.3
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 45
          periodSeconds: 5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PREFIX_PATH
          value: ""
        - name: MONGODB_HOST
          value: 'mongodb:27017'
        - name: MONGODB_DATABASE
          value: 'keptn'
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
                name: mongodb-credentials
                key: user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mongodb-credentials
                key: password
      - name: distributor
        image: docker.io/keptn/distributor:0.7.3
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 45
          periodSeconds: 5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUBSUB_IMPL
            value: nats
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.>'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
          - name: PUBSUB_RECIPIENT_PATH
            value: '/event'
