---
# Source: keptn/charts/control-plane/templates/quality-gates.yaml
apiVersion: v1
kind: Service
metadata:
  name: lighthouse-service
  labels:
    app.kubernetes.io/name: lighthouse-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane    
    helm.sh/chart: control-plane-0.7.3 
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: lighthouse-service
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: keptn/charts/control-plane/templates/quality-gates.yaml
# lighthouse-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-service
  labels:
    app.kubernetes.io/name: lighthouse-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: 0.7.3
    helm.sh/chart: control-plane-0.7.3 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lighthouse-service
      app.kubernetes.io/instance: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: lighthouse-service
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: 0.7.3
        helm.sh/chart: control-plane-0.7.3         
    spec:
      containers:
        - name: lighthouse-service
          image: docker.io/keptn/lighthouse-service:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: MONGODB_DATASTORE
              value: 'mongodb-datastore:8080'
            - name: ENVIRONMENT
              value: 'production'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: distributor
          image: docker.io/keptn/distributor:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 45
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-lighthouse-service
