---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-default
  labels:
    app.kubernetes.io/name: keptn-default
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-configuration-service
  labels:
    app.kubernetes.io/name: keptn-configuration-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-lighthouse-service
  labels:
    app.kubernetes.io/name: keptn-lighthouse-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-api-service
  labels:
    app.kubernetes.io/name: keptn-api-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-secrets
  labels:
    app.kubernetes.io/name: keptn-manage-secrets
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3 
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-read-metadata
  labels:
    app.kubernetes.io/name: keptn-read-metadata
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3 
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-configmaps
  labels:
    app.kubernetes.io/name: keptn-manage-configmaps
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - get
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-configure-bridge
  labels:
    app.kubernetes.io/name: keptn-configure-bridge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
    resourceNames:
      - "bridge-credentials"
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-lighthouse-service
  labels:
    app.kubernetes.io/name: keptn-lighthouse-service
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-configmaps
subjects:
  - kind: ServiceAccount
    name: keptn-lighthouse-service
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service-configure-bridge
  labels:
    app.kubernetes.io/name: keptn-api-service-configure-bridge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-configure-bridge
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service-metadata
  labels:
    app.kubernetes.io/name: keptn-api-service-metadata
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-metadata
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
---
# Source: keptn/charts/control-plane/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-configuration-service-manage-secrets
  labels:
    app.kubernetes.io/name: keptn-configuration-service-manage-secrets
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-platform-system
    app.kubernetes.io/component: control-plane
    helm.sh/chart: control-plane-0.7.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-configuration-service
