---
# Source: keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/version: "1"
    helm.sh/chart: mongodb-0.7.3
spec:
  replicas: 1
  selector:
    matchLabels:      
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: RELEASE-NAME      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/version: "1"
        helm.sh/chart: mongodb-0.7.3
    spec:
      serviceAccountName: keptn-default
      securityContext:
        fsGroup: 184
      containers:
        - image: docker.io/centos/mongodb-36-centos7:1
          name: mongodb
          env:
            - name: MONGODB_DATABASE
              value: "keptn"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-credentials
                    key: password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-credentials
                    key: admin_password
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: mongodata
      restartPolicy: Always
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata
