apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
spec:
  template:
    spec:
      containers:
        - name: configuration-service
          env:
            - name: MONGODB_USER
              value: keptn
              valueFrom: null
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-keptn-credentials
