repo_url: https://github.com/flanksource/karina
repo_name: karina
docs_dir: ./
site_name: karina
theme:
  name: "material"
  palette:
    primary: "royalblue"
  logo: "img/favicon.png"
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    # - git-revision-date:
    #     enabled_if_env: CI
extra:
  generator: false
  domain: 127.0.0.1.nip.io
  kubernetes:
    version: v1.18.15
  support:
    email: email group(s) etc
    channel: Slack, MS Teams, etc...
  filebeat:
    prefix: co.elastic.logs

  social:
    - type: "github"
      link: "https://github.com/flanksource"
      icon: fontawesome/brands/github-alt
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - codehilite:
      linenums: true
  - toc:
      permalink: true
plugins:
  - search
  - autolinks
  - macros:
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
      j2_variable_start_string: "%%{"
      j2_variable_end_string: "}%%"
  - same-dir
extra_css:
  - overrides/style.css
nav:
  - User Guide:
      - Overview: ./user-guide/index.md
      - Monitoring:
          - Canary Checker: ./user-guide/canary-checker.md
          - Prometheus: ./user-guide/prometheus.md
          - Logging: ./user-guide/logging.md
      - CI/CD:
          - Dynamic Namespaces: ./user-guide/dynamic-namespaces.md
          - GitOps: ./user-guide/gitops.md
      - Ingress:
          - Overview: ./user-guide/ingress.md
          - TLS: ./user-guide/tls.md

      - Reference:
          Annotations: ./user-guide/annotations.md

  - Administrator Guide:
      - Overview: ./admin-guide/index.md
      - Provisioning:
          - Kind: ./admin-guide/provisioning/kind.md
          - vSphere: ./admin-guide/provisioning/vsphere.md
          - More:
              - vCenter Connectivity: ./admin-guide/provisioning/vcenter.md
              - Master Discovery: ./admin-guide/provisioning/master-discovery.md
              - Load Balancing: ./admin-guide/provisioning/load-balancing.md
              - DNS: ./admin-guide/provisioning/dns.md
              - Machine Images: ./admin-guide/provisioning/machine-images.md

      - Monitoring:
          - Prometheus: ./admin-guide/prometheus.md
          - Canary Checker: ./admin-guide/canary-checker.md
          - Logging: ./admin-guide/logging.md
          - Thanos: ./admin-guide/thanos.md

      - Authentication:
          - Decentralized Auth: ./admin-guide/provisioning/ca.md
          - Single Sign On: ./admin-guide/sso.md

      - Multi Cluster:
          - Discovery: ./admin-guide/provisioning/master-discovery.md

      - Networking:
          - Calico: ./admin-guide/calico.md
          - Antrea: ./admin-guide/antrea.md
          - NSX-T NCP: ./admin-guide/ncp.md
          - Ingress: ./admin-guide/ingress.md
          - Istio: ./admin-guide/istio.md

      - Storage:
          - vSphere: ./admin-guide/vsphere.md
          - Local Path: ./admin-guide/local-path.md
          - Minio: ./admin-guide/minio.md

      - Security:
          - Auditing: ./admin-guide/auditing.md
          - Encryption: ./admin-guide/encryption.md
          - Sealed Secrets: ./admin-guide/sealed-secrets.md
          - Vault: ./admin-guide/vault.md
          - OPA/Gatekeeper: ./admin-guide/opa.md

      - Configuration: ./admin-guide/configuration.md
      - Troubleshooting:
          - Checklist: ./admin-guide/troubleshooting.md
  - Operators:
      - Elastic: ./operators/elastic.md
      - Git: ./operators/git.md
      - Harbor: ./operators/harbor.md
      - Platform: ./operators/platform.md
      - Postgres: ./operators/postgres.md
      - RabbitMQ: ./operators/rabbitmq.md
      - Redis: ./operators/redis.md
      - Template:
          Getting Started: ./operators/template/index.md
          Syntax: ./operators/template/syntax.md
          Chaining: ./operators/template/chaining.md
  - Reference: ./reference/config.md
