name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make pack
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
      - name: filename check
        run: go run test/linter/main.go
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
      - run: make pack build-api-docs build-docs
