name: Self Hosted E2E

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"

jobs:
  binary:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.12.0
    steps:
      - uses: actions/checkout@main
      - run: make linux
      - uses: actions/upload-artifact@v2
        with:
          name: karina
          path: ./.bin/karina
  test:
    runs-on: [self-hosted]
    if: "! contains(toJSON(github.event.commits.*.message), 'skip-e2e')"
    needs: binary
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.18.8
        suite:
          - minimal
          # - minimal-antrea
          - monitoring
          - harbor2
          # - postgres
          # - elastic
          # - security
          - platform
          # - nosql
          # - cicd
        # include:
        #   - k8s: v1.17.5
        #     suite: minimal
        #   - k8s: v1.17.5
        #     suite: minimal-antrea
        #   - k8s: v1.17.5
        #     suite: monitoring
        #   - k8s: v1.16.9
        #     suite: minimal
        #   - k8s: v1.16.9
        #     suite: monitoring
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v2
        with:
          name: karina
          path: ./.bin
      - name: Run e2e testing script
        env:
          CACHE_DIR: /runner/_work
          GIT_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          SUITE: ${{ matrix.suite }}
          KUBERNETES_VERSION: ${{matrix.k8s}}
          BUILD: test (${{matrix.k8s}}, ${{ matrix.suite }})
        run: ./test/test.sh
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: test-results-${{matrix.k8s}}-${{matrix.suite}}
          path: test-results/
      - name: Upload snapshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: snapshot-${{matrix.k8s}}-${{matrix.suite}}
          path: artifacts/snapshot.zip
